### ISSUE TITLE
problem with std.code.maintindex.simple (but great tool otherwise!)

### ISSUE THREAD

**Issue by jbo3** [metrixplusplus/metrixplusplus#13]
Great tool! We use it to evaluate the cyclomatic complexity and lines of code for C and C++ code, embedded and desktop. Very handy and simple to use.

One thing: std.code.maintindex.simple is not working, i think.
```
test > cat test.c
int f0() {
    return 0;
}
test > python3 /c/tools/metrixplusplus/metrixplusplus/metrix++.py collect --std.code.lines.code --std.code.complexity.cyclomatic  --std.code.maintindex.simple
[skipped]
[LOG]: INFO:    Processing: ./test.c
Traceback (most recent call last):
    [skipped]
    File "C:\tools\metrixplusplus\metrixplusplus\mpp\api.py", line 1160, in get_result
        (range_pair[1] == None or sourced_metric <= range_pair[1])):
    TypeError: '<=' not supported between instances of 'NoneType' and 'int'
```
Attached is the output with debug log level.
[debug.log](https://github.com/metrixplusplus/metrixplusplus/files/4613957/debug.log)

**Comment by avkonst** [comment]
Thanks for the ticket. Would you be able to make a fix, verify it and submit pull request? The project is community driven, we do not have a dedicated developer for this at the moment.
