### ISSUE TITLE
UnicodeDecodeError raised for source code file in UTF-8 format

### ISSUE THREAD

**Issue by iazarov** [metrixplusplus/metrixplusplus#16]
UnicodeDecodeError appears on the UTF-8 file analysis.

  File ".../metrixplusplus/ext/std/tools/collect.py", line 146, in run_per_file
    checksum = binascii.crc32(text.encode('utf8')) & 0xffffffff # to match python 3
UnicodeDecodeError: 'ascii' codec can't decode byte 0xef in position 0: ordinal not in range(128)

  File ".../metrixplusplus/ext/std/code/cs.py", line 110, in finalize_block
    crc32 = binascii.crc32(text[start_pos:child['start']].encode('utf8'), crc32)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xef in position 0: ordinal not in range(128)

  File ".../metrixplusplus/ext/std/code/cpp.py", line 99, in finalize_block
    crc32 = binascii.crc32(text[start_pos:child['start']].encode('utf8'), crc32)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 91: ordinal not in range(128)

The possible fix could be replacing ".encode('utf8')" into ".decode('utf8').encode('utf8')" in all places, if it does not change the handling algorithm.

**Comment by avkonst** [comment]
Hello. Would you be able to fix it and verify the fix using your code base and tests from Metrix++? The project is community driven. If you would like it fix, please fix it and submit pull request. Thanks!
