### ISSUE TITLE
Create pypi package for metrix++

### ISSUE THREAD

**Issue by snikulov** [metrixplusplus/metrixplusplus#19]
It'll be great to have the possibility to install/upgrade metrix++ using pip tool from PyPI.org

**Comment by avkonst** [comment]
Hi @prozessorkern. Do you think it is feasible? worth doing?

**Comment by prozessorkern** [comment]
Seems interesting to me.

I will try to look at this during the next week.
At first glance it does not look too complicated.

**Comment by prozessorkern** [comment]
I added a setup script and github action to deploy metrix++ to pypi
https://pypi.org/project/metrixpp/

For testing I added a packet versino 0.0.1a.
The real deployment will be triggered during the next release.

@snikulov please check if this works for you.

**Comment by snikulov** [comment]
@prozessorkern Thank you!
```
$ python --version
Python 3.8.3
$ pip install metrixpp --user
.... installed: metrixpp in /home/snikulov/.local/lib/python3.8/site-packages (0.0.1a0)
$ metrix++
Usage: python metrix++ --help
       python metrix++ <action> --help
       python metrix++ <action> [options] -- [path 1] ... [path N]

Actions: 
  collect
  export
  info
  limit
  view

metrix++: error: Mandatory action argument required

```
