### ISSUE TITLE
More documentation available?

### ISSUE THREAD

**Issue by mstoerzel** [metrixplusplus/metrixplusplus#24]
Hi there,

after I walked through the tutorials I'm even more impressed by the possibilities of this tooling. I was just wondering if there is some more documentation available, like api description. Would you please point me to if I just missed where to look it up.

Thanks,

Marc

**Comment by avkonst** [comment]
There is a website only. Sorry, there are no docs for API, but the code is quite easy for more or less experienced Python programmer. The project is largely driven by community contributions. If you would like to improve something, you are welcome! Let me know.

If you have got questions, we can try to answer it here.

**Comment by mstoerzel** [comment]
Hi,

yes, I'd like to contribute and please regard the following as my first contribution. As this is not related to the code in the repo I'm posting it here.

Regarding the post-analysis tool plugin tutorial I may suggest to add the following;
line 27ff:
`    def _compare_file(self, file_data, loader, loader_prev):`
...
`        else:
            return 0`
Else path may be triggered if (by mistake) --db-file and --db-file-prev point to the same file.

and in line 41ff; 
'def _compare_file_regions(self, file_data, file_data_prev):'
I propose to change the last line before the return statement to something like
`                cur_lines = region.get_data('std.code.lines', 'total')`
`                prev_lines = region_prev.get_data('std.code.lines', 'total')`
`                if (cur_lines != None) and (prev_lines != None):`
`                    result += cur_lines - prev_lines` 
This would prevent an unwanted exception if e.g. the collect tool was issued with --std.code.lines.code instead of ...lines.total.

These two minor changes would make the example more fool save.

**Comment by avkonst** [comment]
Hi, I have sent you an invitation to join. Keep @prozessorkern  in the loop. Thanks.

**Comment by avkonst** [comment]
feel free to update docs in markdown format in docs directory
