### ISSUE TITLE
convert html docs to Markdown

### ISSUE THREAD

**Issue by mskonst** [metrixplusplus/metrixplusplus#25]
Placeholder.

**Comment by avkonst** [comment]
Hi, @prozessorkern @mstoerzel please welcome Marina (@mskonst) to the team. She will work on converting [the website docs](https://metrixplusplus.github.io/home.html) to [docusaurus 2 powered docs](https://v2.docusaurus.io/docs/). The sources for docs will be in markdown format. Docusaurus will render nice looking website from markdown. [Here is an example of docusaurus docs for another project](https://hookstate.js.org/), which I look after.

**Comment by avkonst** [comment]
merged Marina's work to master branch
