### ISSUE TITLE
How to exclude folders from collecting data

### ISSUE THREAD

**Issue by holyraspi** [metrixplusplus/metrixplusplus#27]
Hello!, after some initial problems I got the tool working. 

I have seen that you can exclude files with the help of --exclude-files. How can you exclude folders and all files inside them ?
 
For example:
folder alpha\main.c
folder beta\functions.c

--exclude-files=alpha\*.c ???

I would appreciate an answer. Thank you very much!

**Comment by avkonst** [comment]
the exclude files accepts a regular expression. If a regular expression matches the path to a file it will be excluded.
Also see this coming: https://github.com/metrixplusplus/metrixplusplus/pull/26

**Comment by holyraspi** [comment]
the patch works fine, thanks
