### ISSUE TITLE
Relation between number of comments and number of statements

### ISSUE THREAD

**Issue by holyraspi** [metrixplusplus/metrixplusplus#30]
Hello,

can you tell me if it is possible to implement the ratio of the number of comments and the number of statements (per function)?

ratio = std.code.lines.comments / std.code.lines.code 

I would like to set this ratio as a warning if the ratio is smaller than 0.2.

**Comment by avkonst** [comment]
1. I should be possible to write new metrics plugin which depends on the existing one and add one more 'ratio' field, which you could you later for the warning. The project is driven by the effort of contributors. Would you like to contribute and add such a plugin?

2. Also, it is your decision... but I advise that the threshold you would like to propose is not a good one from the quality control point of view. I have seen the cases when developers started putting useless comments, which actually do more harm than good. The best written code is the one which does not require comments to understand it. But up to you.

**Comment by holyraspi** [comment]
Okay, thanks for your fast response. Unfortunately my customer requires this special metric :/ 

Thanks.

**Comment by avkonst** [comment]
You still can have it! Contribute to the source code..

**Comment by avkonst** [comment]
@holyraspi Could you please create pull request? 
@prozessorkern I have looked at this briefly. Looks reasonable. Only not sure if the new class in the api.py file is required or not. I thought a plugin can return new calculated value without introducing new counter type. But have a look what is the most reasonable thing to do. Maybe this ratio class can be reused elsewhere.

**Comment by holyraspi** [comment]
@avkonst  
Unfortunately I am not the Python expert, so I can only confirm that it could have been better implemented.
I will try to do a pull-request shortly.

FYI: To activate the ratio comment lines to code lines, use the following argument: --std.code.ratio.commentcode

The following must also be activated:
--std.code.lines.code --std.code.lines.comments

**Comment by avkonst** [comment]
No worries at all. Your code is fine. I have only given comments for consideration. Please wait for @prozessorkern to review it too. Pull request will help.
