### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf2 in position 564: invalid continuation byte

### ISSUE THREAD

**Issue by dourand** [metrixplusplus/metrixplusplus#55]
Tried to use it on some C++ packages. Is there any way to fix it? The executables of the source code runs normally when built.

**Comment by brodym** [comment]
This is probably the same as issue #43.  I just posted something to that issue with respect to how I was able to hack my way around all these unicode errors...

**Comment by dourand** [comment]
Personally I used iconv to turn ISO-8859-15(in my case) to utf8 and it worked, but it is kind of annoying to do that with many files of different packages.
