### ISSUE TITLE
PyPi version of Metrixpp does not support --std.code.ratio.comments

### ISSUE THREAD

**Issue by glentehofste** [metrixplusplus/metrixplusplus#60]
The PyPi version of Metrix++ (v1.7.1) as installed with pip does not support the `--std.code.ratio.comments` option as mentioned [on the website](https://metrixplusplus.github.io/metrixplusplus/docs/01-u-overview).

I get back the following error: `metrix++: error: no such option: --std.code.ratio.comments`

When checking Metrix++ out from source however, the option does work! 
I quickly checked the commits on the master branch and saw that this feature (which is documented on the website(!)) is not actually part of any 'official' release. Please consider making this more clear to avoid these kind of issues.

**Comment by prozessorkern** [comment]
Just released a new version on pypi - this should fix your issue.
