### ISSUE TITLE
Provide setup.py for installing into /usr/?

### ISSUE THREAD

**Issue by petterreinholdtsen** [metrixplusplus/metrixplusplus#9]
Hi.  Please consider providing a setup.py script to install the program and support libraries into /usr/.

**Comment by avkonst** [comment]
Hi, please consider to contribute. The tool self installs on first run. So place it to the usr directory and run it once. I believe it will make it installed the way you want it. Also there is Debian package as far as I know.

**Comment by petterreinholdtsen** [comment]
Not quite sure what you are describing here.  I considered packaging metrixplusplus for Debian, but wanted to see if there was any activity first, and point out a missing feature that would make Debian packaging easier.  First response after two months is cause for worry about future maintenance, I must admit.

Anyway, which Debian package did you have in mind?  I would like to check it out.

**Comment by avkonst** [comment]
I am involved with the project in low maintenance mode. at the moment I do not have plans to develop it more. However the tool is useful as it is now. @prozessorkern offered to contribute to bug fixing and other extensions he needs. I have requested Debian guys who contacted me in the past regarding packaging.

**Comment by avkonst** [comment]
The answer to the ticket is:
"The tool self installs on first run. So place it to the usr directory and run it once. It should make it installed in the desired location."
